text[0] = "A drawner";
text[1] = "It's not your!";
text[2] = "I think Papyrus would like this";
speaker[0] = 1;
player_sprite [0] = sInvisible;
speaker[1] = 1;
player_sprite [1] = sInvisible;
speaker[2] = 1;
player_sprite [2] = sInvisible;